---
- name: Kubeadm Control Plane Node | Generate join command for control plane nodes
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command
  no_log: true
  when: inventory_hostname in groups['control'][0]

- name: Kubeadm Control Plane Node | Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    join_cmd: '{{ join_command.stdout }}'
    cacheable: true
  delegate_to: localhost
  delegate_facts: true
  when: inventory_hostname in groups['control'][0]

- name: Kubeadm Control Plane Node | Join control plane nodes to initial control plane
  ansible.builtin.shell: "{{ hostvars['localhost'].join_cmd }}"
  when: inventory_hostname in groups['control'][1:]
