---
- name: Kubeadm Worker Node | Generate join command for worker nodes
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command
  no_log: true
  when: inventory_hostname in groups['initial']

- name: Kubeadm Worker Node | Setting facts so that they will be persisted in the fact cache
  ansible.builtin.set_fact:
    join_cmd: '{{ join_command.stdout }}'
    cacheable: true
  delegate_to: localhost
  delegate_facts: true
  when: inventory_hostname in groups['initial']

- name: Kubeadm Worker Node | Join worker nodes to control plane
  ansible.builtin.shell: "{{ hostvars['localhost'].join_cmd }}"
  when: inventory_hostname in groups['worker']